events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=5s;  # DNS interne Docker

    server {
        listen 80;

        location / {
            set $backend "http://api:8081";  # force la re-résolution

            proxy_pass             $backend;
            proxy_set_header       Host              $host;
            proxy_set_header       X-Real-IP         $remote_addr;
            proxy_set_header       X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_connect_timeout  10s;
            proxy_read_timeout     60s;
        }
    }
}