version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    env_file:
      - .env.mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build: .
    restart: always
    env_file:
      - .env.api
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    build: ./nginx           # <--- On build notre propre image Nginx
    container_name: nginx_lb
    restart: always
    ports:
      - "8888:80"
    # SUPPRIMEZ la section volumes ici car la config est maintenant DANS l'image
    depends_on:
      - api
    networks:
      - app-network
volumes:
  mysql_data:

networks:
  app-network: